### ISSUE TITLE
js minify

### ISSUE THREAD

**Issue by rusalexd** [kosik/kosik.github.io#1]
Необходимо объединить подключение пакетов, дабы не подгружать по-отдельности все пакеты (т.к. это долго), а одним запросом загрузить сразу все необходимые (так быстрее).
Для реализации необходимо сравнить способы получения данного результата средствами dojo и сторонними (скорее всего gulp)
Планирую в среду (6 апреля) закончить.

**Comment by zainiac** [comment]
Опиши свою задачу: как её понимаешь, как думаешь решить, срок выполнения, какие ресурсы (помощь возможно) нужны.

**Comment by rusalexd** [comment]
Забыл отписать. Андрею В отдал настроенный grunt (grunt так как sails из коробки лучше с ним дружит). Минификация JS настроена.

**Comment by kosik** [comment]
А как это работает? Нужно посмотреть. Демонстрацию, так сказать...

**Comment by zainiac** [comment]
Надеюсь, что работает, как в документации, Сергей.
