### ISSUE TITLE
Implements 

### ISSUE THREAD

**Issue by PolinaLT** [kosik/kosik.github.io#3]
POST secure/dataUpload
POST secure/attachPresentation
POST secure/loadContent
POST content/{postId}

**Comment by zainiac** [comment]
Опиши свою задачу: как её понимаешь, как думаешь решить, срок выполнения, какие ресурсы (помощь возможно) нужны.

**Comment by blrB** [comment]
ну реализацию Transport функций я вроде сделал(еще надо протестировать, но сайт сейчас лежит), сборка jsonObject уже зависит от будущей реализации верстки, которой пока нет
